name: Late Change Approval

on:
  pull_request:
    types: [labeled]

jobs:
  notify-pr:
    runs-on: ubuntu-latest

    if: github.event.label.name == 'late-change-request'

    steps:
      - name: Request Late Change Approval
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --body "🔔 @haydenjtb, this pull request is request a late change approval."
